import type { PXSFrame } from '../../store/pxs-store';
import type { GalleryEntry } from '../../store/gallery-store';
import pixcelLogo from '../defaults/pixcel-logo.json';
import smiley16 from './smiley-16.json';
import heart20 from './heart-20.json';
import star24 from './star-24.json';
import mushroom16 from './mushroom-16.json';
import dog16 from './dog-16.json';
import banana16 from './banana-16.json';
import lambo32 from './lambo-32.json';
import lamboPipeline32 from './lambo-pipeline-32.json';
import lamboPipeline2_32 from './lambo-pipeline2-32.json';
import monkey32 from './monkey-32.json';
import monkeyFace32 from './monkey-face-32.json';
import monkeyFaceAgent32 from './monkey-face-agent-32.json';
import robotAgent16 from './robot-agent-16.json';
import catAgent16 from './cat-agent-16.json';
import robot32 from './robot-32.json';
import cat32 from './cat-32.json';
import wizardAnchored32 from './wizard-anchored-32.json';
import raceCar32 from './race-car-32.json';
import raceCarPipeline32 from './race-car-pipeline-32.json';
import saguaro16 from './saguaro-16.json';
import appleLive16 from './apple-live-16.json';
import dragonLive48 from './dragon-live-48.json';
import owlLive32 from './owl-live-32.json';
import dragonLive48b from './dragon-live-48b.json';
import trexClaudeCode32 from './trex-claudecode-32.json';

export type { GalleryEntry };

/**
 * Curated PXS art (the built-in seeds). AI/user-generated pieces are added at runtime via
 * the gallery store (src/store/gallery-store.ts). To add a built-in: save `your-art.json`
 * here (PXSFrame shape), then append an entry below with `builtin: true`.
 */
export const GALLERY_ENTRIES: GalleryEntry[] = [
  {
    id: 'pixcel-logo',
    title: 'Pixcel Logo',
    prompt: 'Default studio wordmark (landing artwork)',
    promptBy: 'human',
    composedBy: 'human',
    frame: pixcelLogo as PXSFrame,
    builtin: true,
  },
  {
    id: 'smiley-16',
    title: 'Smiley',
    prompt:
      'Cheerful pixel smiley on dark background — yellow face, simple eyes and grin',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: smiley16 as PXSFrame,
    builtin: true,
  },
  {
    id: 'heart-20',
    title: 'Pixel Heart',
    prompt: 'Small red pixel heart icon, retro game style, centered on dark canvas',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: heart20 as PXSFrame,
    builtin: true,
  },
  {
    id: 'star-24',
    title: 'Golden Star',
    prompt: 'Five-point golden star centered on a dark night-sky grid',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: star24 as PXSFrame,
    builtin: true,
  },
  {
    id: 'mushroom-16',
    title: 'Toadstool',
    prompt:
      'Classic retro mushroom — red cap with white spots and a cream stem, centered on a dark canvas',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: mushroom16 as PXSFrame,
    builtin: true,
  },
  {
    id: 'dog-16',
    title: 'Puppy',
    prompt:
      'Cute front-facing sitting dog with floppy ears, cream muzzle and paws, on a dark canvas',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: dog16 as PXSFrame,
    builtin: true,
  },
  {
    id: 'banana-16',
    title: 'Banana',
    prompt:
      'A ripe yellow banana — curved crescent with a brown stem and blossom tip, on a dark canvas',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: banana16 as PXSFrame,
    builtin: true,
  },
  {
    id: 'lambo-32',
    title: 'Lambo',
    prompt:
      'Iconic front view of a yellow Lamborghini Gallardo — wide low wedge, slanted headlights, three lower air intakes, 32x32',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: lambo32 as PXSFrame,
    builtin: true,
  },
  {
    id: 'lambo-pipeline-32',
    title: 'Lambo (Pipeline)',
    prompt: 'a yellow Lamborghini Gallardo, front view — generated by the in-app pipeline (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: lamboPipeline32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'lambo-pipeline2-32',
    title: 'Lambo (Pipeline v2)',
    prompt: 'a yellow Lamborghini Gallardo, front view — fresh pipeline run (streaming fix, Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: lamboPipeline2_32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'monkey-32',
    title: 'Monkey',
    prompt:
      'A cute sitting monkey, front view — round head, big ears, heart-shaped face, belly, hands, feet and a curled tail, 32x32',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: monkey32 as PXSFrame,
    builtin: true,
  },
  {
    id: 'monkey-face-32',
    title: 'Monkey Face',
    prompt:
      'An expressive monkey face, front view — big ears, big eyes with highlights, nose, smile, and rosy cheeks, 32x32',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: monkeyFace32 as PXSFrame,
    builtin: true,
  },
  {
    id: 'monkey-face-agent-32',
    title: 'Monkey Face (Agent Loop)',
    prompt: 'monkey face — generated by the open agentic loop (vision OODA + exemplar), Opus 4.8',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: monkeyFaceAgent32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'robot-agent-16',
    title: 'Robot (Agent Loop)',
    prompt: 'a robot — open agentic loop, converged in 2 drafts (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: robotAgent16 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'cat-agent-16',
    title: 'Cat (Agent Loop)',
    prompt: 'a cat — open agentic loop, draft 2 (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: catAgent16 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'robot-32',
    title: 'Robot',
    prompt:
      'A friendly retro robot, front view — antenna with red light, glowing cyan eyes, grille mouth, chest light, arms and legs, 32x32',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: robot32 as PXSFrame,
    builtin: true,
  },
  {
    id: 'cat-32',
    title: 'Cat',
    prompt:
      'A cute sitting orange tabby cat, front view — ears with pink inner, green eyes, pink nose, cream belly, curling tail and paws, 32x32',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: cat32 as PXSFrame,
    builtin: true,
  },
  {
    id: 'wizard-anchored-32',
    title: 'Wizard (Anchored 16→32)',
    prompt: 'a wizard — anchored progressive refinement: identity locked at 16², detailed at 32² (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: wizardAnchored32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'race-car-32',
    title: 'Race Car',
    prompt:
      'A red side-view race car — sleek low body, cockpit windshield, rear spoiler, white number roundel, two wheels, 32x32',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: raceCar32 as PXSFrame,
    builtin: true,
  },
  {
    id: 'race-car-pipeline-32',
    title: 'Race Car (Pipeline)',
    prompt: 'a race car — in-app pipeline, pure max reasoning, no exemplar (Opus 4.8, high effort)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: raceCarPipeline32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'saguaro-16',
    title: 'Saguaro Cactus',
    prompt: 'a green cactus — in-app pipeline, pure max reasoning (Opus 4.8, high effort)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: saguaro16 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'apple-live-16',
    title: 'Apple (Live)',
    prompt: 'a red apple — live-artisan: eyes-open, painted gesture by gesture on an erasable canvas (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: appleLive16 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'dragon-live-48',
    title: 'Dragon (Live 48²)',
    prompt: 'a majestic dragon — live-artisan: eyes-open, 18 gestures on an erasable 48×48 canvas (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: dragonLive48 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'owl-live-32',
    title: 'Owl (Live Cascade)',
    prompt: 'an owl — live-artisan sculptor cascade: eyes-open, 6 phases (shape→qa), independent reviewer (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: owlLive32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'dragon-live-48b',
    title: 'Dragon (Live Cascade)',
    prompt: 'a majestic dragon — live sculptor cascade, 48², reached DETAIL (62 gestures) before credits ran out (Opus 4.8)',
    promptBy: 'human',
    composedBy: 'ai-composer',
    frame: dragonLive48b as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
  {
    id: 'trex-claudecode-32',
    title: 'T-Rex (Claude Code)',
    prompt:
      'a T-rex — hand-authored by Claude Code via the eyes-open artisan loop at full reasoning (9 drafts, 32²). The quality bar the in-app engine targets.',
    promptBy: 'human',
    composedBy: 'human',
    frame: trexClaudeCode32 as PXSFrame,
    builtin: true,
    model: 'claude-opus-4-8',
  },
];
