'use client';

/* ─────────────────────────────────────────────────────────────────────────────
 * Pixcel CHAT SPLASH — FROZEN (gold reference, 2026-06-27).
 * Layout, content, copy, and the grid background are LOCKED. Only GLOBAL token/CSS
 * changes (tokens.css / globals.css) may flow through here. Do not edit this file's
 * structure or copy without Brian's explicit say-so.
 * ───────────────────────────────────────────────────────────────────────────── */

import { useState } from 'react';
import NavRail from './NavRail';
import PixcelLogo from './PixcelLogo';

interface Props {
  onEnter: () => void;
  /** First name of the signed-in user (from auth). Greeting drops the name when absent. */
  userName?: string;
}

/* ── Iconography (Claude Design handoff): Lucide line icons (stroke 2, currentColor,
   viewBox 0 0 24 24). Only the prompt-bar glyphs live here now — the nav rail (mark +
   section/utility icons) is the shared <NavRail> component. ── */
type IconName = 'send' | 'plus';

const PATHS: Record<IconName, string[]> = {
  send: ['M5 12h14', 'm12 5 7 7-7 7'],
  plus: ['M5 12h14', 'M12 5v14'],
};

function Ic({ name, size = 20 }: { name: IconName; size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      {PATHS[name].map((d, i) => <path key={i} d={d} />)}
    </svg>
  );
}

export default function LandingPage({ onEnter, userName }: Props) {
  const [draft, setDraft] = useState('');

  return (
    <div className="pxl-root flex h-screen overflow-hidden">
      <style>{`
        .pxl-root { background: var(--a2ui-bg-app); color: var(--a2ui-text-primary); font-family: var(--a2ui-font-family); -webkit-font-smoothing: antialiased; }
        .pxl-root ::selection { background: var(--a2ui-accent-subtle); }
        .pxl-gridbg { background-image: linear-gradient(rgba(255,255,255,0.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.025) 1px,transparent 1px); background-size:28px 28px; -webkit-mask-image:radial-gradient(circle at 50% 34%,black,transparent 70%); mask-image:radial-gradient(circle at 50% 34%,black,transparent 70%); }
        /* Rail styles (.pxl-rail/.pxl-navbtn/etc.) now live in the shared <NavRail>. */
        .pxl-promptbar { background: var(--a2ui-bg-input); border: 1px solid var(--a2ui-border-default); transition: border-color var(--a2ui-transition-fast), box-shadow var(--a2ui-transition-fast); }
        .pxl-promptbar:focus-within { border-color: var(--a2ui-accent); box-shadow: 0 0 0 3px var(--a2ui-accent-subtle); }
        .pxl-input { background: transparent; color: var(--a2ui-text-primary); }
        .pxl-input::placeholder { color: var(--a2ui-text-tertiary); }
        .pxl-iconbtn { color: var(--a2ui-text-tertiary); border-radius: 9999px; transition: color var(--a2ui-transition-fast), background var(--a2ui-transition-fast); }
        .pxl-iconbtn:hover { color: var(--a2ui-text-secondary); background: var(--a2ui-bg-hover); }
        .pxl-send { background: var(--a2ui-accent); color: var(--a2ui-text-inverse); border-radius: 9999px; transition: background var(--a2ui-transition-fast); }
        .pxl-send:hover { background: var(--a2ui-accent-hover); }
        .pxl-chip { background: var(--a2ui-bg-secondary); border: 1px solid var(--a2ui-border-default); color: var(--a2ui-text-secondary); border-radius: var(--a2ui-radius-full); transition: border-color var(--a2ui-transition-fast), color var(--a2ui-transition-fast); }
        .pxl-chip:hover { border-color: var(--a2ui-border-strong); color: var(--a2ui-text-primary); }
      `}</style>

      {/* Primary nav rail — the shared <NavRail> (single source of truth). On the splash
          you're in Chat, so Chat carries the active state; every item enters the app. */}
      <NavRail
        activeSection="chat"
        onHome={() => {}}
        onSection={() => onEnter()}
        onUtility={() => onEnter()}
      />

      {/* Main column — the Chat splash */}
      <div className="relative flex-1 flex flex-col min-w-0">
        <div className="pxl-gridbg pointer-events-none absolute inset-0" />

        <div className="relative flex-1 flex flex-col items-center justify-center px-6">
          {/* Big, centered Pixcel wordmark (Google-style). Single swap point for a
              future animated "Doodle" — see PixcelLogo. */}
          <PixcelLogo height={84} className="mb-7" />

          {/* The universal ask */}
          <h1 style={{ margin: 0, fontSize: 'clamp(28px, 3.6vw, 36px)', fontWeight: 400, letterSpacing: '-0.01em', textAlign: 'center' }}>
            {userName ? `How can I help you today, ${userName}?` : 'How can I help you today?'}
          </h1>

          {/* Hero prompt bar — Google-style single search; placeholder carries the supporting text */}
          <form
            onSubmit={(e) => { e.preventDefault(); onEnter(); }}
            className="pxl-promptbar mt-7 flex w-full max-w-2xl items-center gap-2 rounded-full px-3.5 py-2.5"
          >
            <button type="button" onClick={onEnter} className="pxl-iconbtn flex h-9 w-9 items-center justify-center shrink-0" title="Attach"><Ic name="plus" size={20} /></button>
            <input
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="Ask me anything…"
              className="pxl-input min-w-0 flex-1 text-[15px] outline-none"
            />
            <button type="submit" className="pxl-send flex h-9 w-9 items-center justify-center shrink-0" title="Send"><Ic name="send" size={16} /></button>
          </form>
        </div>
      </div>
    </div>
  );
}
