'use client';

/* ─────────────────────────────────────────────────────────────────────────────
 * Pixcel CHAT SPLASH — FROZEN (gold reference, 2026-06-27).
 * Layout, content, copy, and the grid background are LOCKED. Only GLOBAL token/CSS
 * changes (tokens.css / globals.css) may flow through here. Do not edit this file's
 * structure or copy without Brian's explicit say-so.
 * ───────────────────────────────────────────────────────────────────────────── */

import { useCallback, useState } from 'react';
import NavRail from './NavRail';
import DigitalWall from './DigitalWall';

interface Props {
  onEnter: (prompt?: string) => void;
}

/* The prompt bar's vertical anchor (the living-canvas "move the search" knob — the agent can
   override `--pxl-prompt-y` later). It now TRACKS the wall logo: the bar sits a fixed gap below the
   wordmark's bottom edge, so it follows the logo as its size/the viewport change. Clamped to a sane
   band. DEFAULT_PROMPT_Y is the pre-measure fallback (≈ the old fixed position, so no first-paint jump). */
const DEFAULT_PROMPT_Y = '62%';
const PROMPT_GAP = 0.06; // small gap below the logo's bottom edge — keeps the bar balanced/close to the logo
const PROMPT_Y_MIN = 0.5; // never above vertical center
const PROMPT_Y_MAX = 0.82;

/* ── Iconography (Claude Design handoff): Lucide line icons (stroke 2, currentColor,
   viewBox 0 0 24 24). Only the prompt-bar glyphs live here now — the nav rail (mark +
   section/utility icons) is the shared <NavRail> component. ── */
type IconName = 'send' | 'plus';

const PATHS: Record<IconName, string[]> = {
  send: ['M5 12h14', 'm12 5 7 7-7 7'],
  plus: ['M5 12h14', 'M12 5v14'],
};

function Ic({ name, size = 20 }: { name: IconName; size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      {PATHS[name].map((d, i) => <path key={i} d={d} />)}
    </svg>
  );
}

export default function LandingPage({ onEnter }: Props) {
  const [draft, setDraft] = useState('');
  const [promptY, setPromptY] = useState(DEFAULT_PROMPT_Y);

  // Anchor the prompt bar a fixed gap below the wall logo's bottom edge (clamped), so it tracks the
  // logo as its size / the viewport change. Stable identity → never churns the wall's render effect.
  const handleLogoLayout = useCallback((box: { bottomFrac: number; visible: boolean }) => {
    const y = box.visible
      ? Math.min(PROMPT_Y_MAX, Math.max(PROMPT_Y_MIN, box.bottomFrac + PROMPT_GAP))
      : 0.7;
    setPromptY(`${(y * 100).toFixed(2)}%`);
  }, []);

  return (
    <div className="pxl-root flex h-screen overflow-hidden">
      <style>{`
        .pxl-root { background: var(--a2ui-bg-app); color: var(--a2ui-text-primary); font-family: var(--a2ui-font-family); -webkit-font-smoothing: antialiased; }
        .pxl-root ::selection { background: var(--a2ui-accent-subtle); }
        /* z-0 background is now the shared <DigitalWall> canvas (the persistent Pixcel digital
           wall), not a flat CSS grid. The logo is painted on that wall; the prompt bar floats above. */
        /* Rail styles (.pxl-rail/.pxl-navbtn/etc.) now live in the shared <NavRail>. */
        .pxl-promptbar { background: var(--a2ui-bg-input); border: 1px solid var(--a2ui-border-default); transition: border-color var(--a2ui-transition-fast), box-shadow var(--a2ui-transition-fast); }
        .pxl-promptbar:focus-within { border-color: var(--a2ui-accent); box-shadow: 0 0 0 3px var(--a2ui-accent-subtle); }
        .pxl-input { background: transparent; color: var(--a2ui-text-primary); }
        .pxl-input::placeholder { color: var(--a2ui-text-tertiary); }
        .pxl-iconbtn { color: var(--a2ui-text-tertiary); border-radius: 9999px; transition: color var(--a2ui-transition-fast), background var(--a2ui-transition-fast); }
        .pxl-iconbtn:hover { color: var(--a2ui-text-secondary); background: var(--a2ui-bg-hover); }
        .pxl-send { background: var(--a2ui-accent); color: var(--a2ui-text-inverse); border-radius: 9999px; transition: background var(--a2ui-transition-fast); }
        .pxl-send:hover { background: var(--a2ui-accent-hover); }
        .pxl-chip { background: var(--a2ui-bg-secondary); border: 1px solid var(--a2ui-border-default); color: var(--a2ui-text-secondary); border-radius: var(--a2ui-radius-full); transition: border-color var(--a2ui-transition-fast), color var(--a2ui-transition-fast); }
        .pxl-chip:hover { border-color: var(--a2ui-border-strong); color: var(--a2ui-text-primary); }
      `}</style>

      {/* Primary nav rail — the shared <NavRail> (single source of truth). On the splash
          you're in Chat, so Chat carries the active state; every item enters the app. */}
      <NavRail
        activeSection="chat"
        onHome={() => {}}
        onSection={() => onEnter()}
        onUtility={() => onEnter()}
      />

      {/* Main column — the Chat splash */}
      <div className="relative flex-1 flex flex-col min-w-0">
        {/* z-0 — the persistent Pixcel digital wall (the REAL low-res Pixcel grid). The Pixcel
            wordmark is painted ON the wall as REAL Pixcel cells (centered, breathing), so it reads
            as DISPLAYED on the screen — there is ONE logo, the real-cell one on the wall. */}
        <div className="pointer-events-none absolute inset-0 z-0">
          {/* ONE screen, ONE resolution (like a TV) — YOU set the resolution; it never auto-changes:
              • pixels = the screen's resolution / chunkiness (lower = chunkier, higher = finer).
              • logoScale = the logo's size; it auto-fits crisp inside that resolution and won't go
                below its minimum (at pixels=88 the floor is ~31% width — raise pixels for a smaller logo). */}
          <DigitalWall className="absolute inset-0 h-full w-full" pixels={88} logoScale={0.25} intensity={0.3} onLogoLayout={handleLogoLayout} />
        </div>

        {/* HIGHER z — the floating UI (prompt bar) above the wall. The layer separation is
            visceral: a digital LED wall behind, the UI floating in front.
            The prompt bar's vertical position is a SINGLE controllable anchor (`--pxl-prompt-y`):
            this is the living-canvas "move the search" knob the agent can drive later. Default is
            the lower third so it sits clear of the wall-painted wordmark (centered above it). */}
        <div className="relative z-10 flex-1" style={{ ['--pxl-prompt-y' as string]: promptY }}>
          <div className="absolute left-0 right-0 flex -translate-y-1/2 justify-center px-6" style={{ top: 'var(--pxl-prompt-y, 70%)' }}>
            {/* Hero prompt bar — Google-style single search; placeholder carries the supporting text */}
            <form
              onSubmit={(e) => { e.preventDefault(); onEnter(draft.trim() || undefined); }}
              className="pxl-promptbar flex w-full max-w-2xl items-center gap-2 rounded-full px-3.5 py-2.5"
            >
              <button type="button" onClick={() => onEnter()} className="pxl-iconbtn flex h-9 w-9 items-center justify-center shrink-0" title="Attach"><Ic name="plus" size={20} /></button>
              <input
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                placeholder="Ask me anything…"
                className="pxl-input min-w-0 flex-1 text-[15px] outline-none"
              />
              <button type="submit" className="pxl-send flex h-9 w-9 items-center justify-center shrink-0" title="Send"><Ic name="send" size={16} /></button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
